name: recipe
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  provider: ^4.1.3+1
  firebase_core: ^0.5.0+1
  cloud_firestore: ^0.14.1+3
  firebase_auth: ^0.18.0+1
  flutter_launcher_icons: ^0.7.5
  enum_to_string: ^1.0.9
  simple_logger: ^1.7.0
  keyboard_actions: ^3.3.1+1
  # 参考：https://github.com/flutter/flutter/issues/65995
  # image_picker: ^0.6.7+12
  image_picker:
    git:
      url: https://github.com/cpboyd/plugins.git
      ref: e9965bd9bfc8e401ee595dd0a9ee6f0940e9b127
      path: packages/image_picker/image_picker
  image_cropper: ^1.3.1
  firebase_storage: ^4.0.1
  flutter_native_image: ^0.0.5+3
  cached_network_image: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true