# ユーザー情報
users:
  documentId: userId = auth.uid
  createdAt: timestamp
  displayname: string
  iconName: string
  iconURL: name
  publicRecipeCount: int
  recipeCount: int
  userId: string

  # 各ユーザーのレシピデータ
  recipes:
    documentId: auto
    userId: userId = auth.uid
    createdAt: timestamp
    updatedAt: timestamp
    name: string
    thumbnailName: string
    thumbnailURL: string
    imageName: string
    imageURL: string
    content: string
    reference: string
    tokenMap: map
    isPublic: boolean

  # 各ユーザーのお気に入りのレシピデータ
  favorite_recipes:
    documentId: documentId = corresponding recipe's documentId
    userId: userId = auth.uid
    createdAt: timestamp
    updatedAt: timestamp
    likedAt: timestamp
    name: string
    thumbnailName: string
    thumbnailURL: string
    imageName: string
    imageURL: string
    content: string
    reference: string
    tokenMap: map
    isPublic: boolean

# 公開設定になったレシピ
public_recipes:
  documentId: documentId = 'public_{corresponding recipe's documentId}'
  userId: userId = auth.uid
  publishedAt: timestamp
  updatedAt: timestamp
  name: string
  thumbnailName: string
  thumbnailURL: string
  imageName: string
  imageURL: string
  content: string
  reference: string
  tokenMap: map
  isPublic: boolean

# ユーザーから送信されたお問い合わせ
contacts:
  documentId: auto
  userId: userId = auth.uid
  email: string
  createdAt: timestamp
  category: string
  content: string

# その他の Firestore 内のデータとして管理できる各設定
settings:
  guest_mode:
    guest_allowed: boolean